### ISSUE TITLE
Close button not activated

### ISSUE THREAD

**Issue by fabrew4n** [finity69x2/cover-control-button-row#2] opened 2020-08-18 08:18 UTC
The close button is not working. The open and stop button is working fine as per normal.

**Comment by finity69x2** [comment] 2020-08-19 04:26
What service does your cover use to close it?

**Comment by fabrew4n** [comment] 2020-08-19 04:29
it uses cover.close_cover. 
i tried to activate it via developer tools->services->cover.close_cover. it works just fine.

**Comment by finity69x2** [comment] 2020-08-19 08:17
strange. I have two garage doors and use it successfully on both of them. And they both use the same service.

I'm not really sure how I can help you troubleshoot it since both of my covers work with it. I'll ask in the forum post to see if anyone else is having any issue with it to see if I can help narrow down the cause.

**Comment by fabrew4n** [comment] 2020-08-19 08:25
Alrights.. no problem..will try to re install and see if its solved..

**Comment by fabrew4n** [comment] 2020-08-19 12:04
It seems that the close btn nv went to disable when open selected. And selected btn nv change color when activated..

**Comment by finity69x2** [comment] 2020-08-20 03:52
The disabled and color are controlled via the cover state.

For example, when the cover state is open the open button is disabled and the open button lights up with the active color and the close button goes to the inactive color.

And of course the close functionality is just the opposite.

Is that not what you are seeing?

**Comment by fabrew4n** [comment] 2020-08-20 04:06
> The disabled and color are controlled via the cover state.
> 
> For example, when the cover state is open the open button is disabled and the open button lights up with the active color and the close button goes to the inactive color.
> 
> And of course the close functionality is just the opposite.
> 
> Is that not what you are seeing?

nope. i understand the functionality and i am not seeing them. when i activated the open, it just stays the same color. and the close button is always on at its active color. 
when i activate the open, the curtain did open. and when i activate stop, it stopped. i am unable to activate the close btn.

**Comment by fabrew4n** [comment] 2020-08-20 04:07
![hacs4](https://user-images.githubusercontent.com/47353708/90715706-aad5a780-e2dd-11ea-885e-ed99d8006133.JPG)

this i when i activated the open btn.

**Comment by finity69x2** [comment] 2020-09-07 03:08
Sorry I got busy and forgot about this. 

Did you ever get it figured out?

**Comment by fabrew4n** [comment] 2020-09-07 11:33
> Sorry I got busy and forgot about this.
> 
> Did you ever get it figured out?

Nope. Didnt managed to figure it out.

**Comment by finity69x2** [comment] 2020-09-07 14:32
What is the state in the states page for the cover when you are trying to close the cover?

**Comment by fabrew4n** [comment] 2020-09-07 15:17
When open is opening.. and close is closing.. and when stop is unknown..

**Comment by finity69x2** [comment] 2020-09-07 16:36
There's your problem.

the plugin expects the entity states to be "open" and "closed" to report and display the correct status indications. I believe that those are the usual states for most cover entities.

Why does your device never report "open/closed"? What brand/model is it? 

Maybe it's something you want to report to the integration developer to get fixed.

**Comment by fabrew4n** [comment] 2020-09-08 00:31
But the states also reported opened and closed..

**Comment by fabrew4n** [comment] 2020-09-08 00:31
Its weird.. i am able to open but not able to close..

**Comment by fabrew4n** [comment] 2020-09-08 00:37
Its zemismart using the tuya app..

**Comment by finity69x2** [comment] 2020-09-08 22:12
again, i'll have to say that the plugin is expecting the states reported to be "open" and "closed". If it's anything else then it won't work.

if the cover reports "closed" then the closed button should be lit up and disabled. And the open button should be active but off. 

If the state is actually reported as "opened" (instead of "open") then the close button won't be enabled.

Can you verify for me what the states are (post a screen shot of the states page when the cover is both open and closed) and I should be able to make the plugin be OK with either state (open or opened).

**Comment by tane64** [comment] 2020-09-24 13:28
Control will work fine aslong the sate is open or closed.
All of my blinds are with position once the state is changed to something like 60 I can only close but not open. Hope you can add the position state.

**Comment by azelinc** [comment] 2020-10-17 12:22
i have the same problem..i can only open, not close. the state is "opening" and "closing" just like @fabrew4n 's

**Comment by finity69x2** [comment] 2020-12-01 18:21
@tane64 

I won't be adding the position because I already have another control row for covers that handle positions (cover-preset-position-row). Try using that one to see if it works for you.

**Comment by finity69x2** [comment] 2020-12-01 18:43
I've looked into this and tried to come up with a solution but I haven't come up with a reasonably straightforward way to accommodate both 'open' & "opening"/"close" & "closing" in the same code.

I think the best way to address this is with getting it fixed in the tuya app.

So unfortunately I'm going to have to close this.

**Closed as completed by finity69x2** 2020-12-01 18:43 UTC

**Comment by slothking87** [comment] 2022-04-03 08:35
This has come up again in my instance. The blinds are either "Opening" or "Closing" even when stopped. It seems to be a limitation of these RF controlled style blinds, that the controller is not able to report the status of them. The blinds themselves are programmed what level to open to, and close to.
