### ISSUE TITLE
Stop button not activated

### ISSUE THREAD

**Issue by JamesDenby** [finity69x2/cover-control-button-row#4] opened 2020-09-18 16:03 UTC
I am using this on my Chamberlain Garage Doors (MyQ). The open works fine, as does the close; however, the STOP button doesn't do anything.

**Comment by JamesDenby** [comment] 2020-09-19 13:19
Here is some more information. I hope it is helpful. 
<img width="398" alt="Custom Cover" src="https://user-images.githubusercontent.com/58569180/93668220-60645980-fa48-11ea-8514-bad1e5afe6d3.png">
<img width="1207" alt="Cover LOG" src="https://user-images.githubusercontent.com/58569180/93668230-69edc180-fa48-11ea-99e3-412e379fc167.png">

**Comment by finity69x2** [comment] 2020-09-27 20:26
I don't use MyQ for exposing my door to HA since they are very unreliable but I just tested my MyQ garage door from the MyQ integration and I don't think the issue is with my control row. I think it's with the MyQ garage doors. They don't seem to expose a "stop" control in HA.

If you don't use my control row but instead use the built-in control then when you operate the door there is no square stop button in that control. There is only the open (up arrow) & close (down arrow) buttons. Further if you open or close the garage door and then immediately call the cover.stop_cover service from the developers tools page then nothing happens and the door continues to open or close.

![ex](https://user-images.githubusercontent.com/32221243/94374964-1a5d6480-00de-11eb-9312-0d78c348c19f.gif)


But I have another garage door that I created using a cover template that includes a stop command and it has the stop button in the built-in control row and my control row will stop it as expected.

![ex1](https://user-images.githubusercontent.com/32221243/94374967-21847280-00de-11eb-8225-bfc45ec6de13.gif)


If you could do some further testing for me to verify that I would appreciate it.

**Comment by finity69x2** [comment] 2020-09-28 21:15
Actually I did some more testing last night...

I found that MyQ does not, in fact, provide a "stop_cover" service to HA.

They don't even provide a way to stop the door from running even thru the MyQ app on my Android.

So I'm pretty certain that it has nothing to do with my control row and everything to do with MyQ. Which is one reason I stopped using it a long time ago.

I'll close this but if you have any other concerns let me know.

**Closed as completed by finity69x2** 2020-09-28 21:15 UTC
